Repository teamneoneko/Cats-Blender-Plugin-Unofficial-, pull requests merged in 2024-07, with the labels that each got.

#137 Cats Blender Plugin 4.2.0.3
  __init__.py
  resources/translations/en_US.json
Labels: Release Candidate

#138 Added shapekey pruner
  resources/translations/en_US.json
  tools/shapekey.py
Labels: Release Candidate, Added, In Progress

#149 Cats Blender Plugin 4.2.1.0
  __init__.py
  blender_manifest.toml
  extentions.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/settings.py
  tools/translations.py
  ui/settings_updates.py
Labels: Release Candidate

#155 4.2.1.1
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/viseme.py
  ui/otheroptions.py
Labels: Release Candidate

#163 Bringing in-line with Blender 3.6 dev
  extentions.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/armature.py
  tools/common.py
  ui/mmdoptions.py
Labels: enhancement

#164 Updated Blender 4.3 dev with latest changes
  extentions.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/armature.py
  tools/common.py
  ui/mmdoptions.py
Labels: enhancement

#165 Add warning popup to MMD model.
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  ui/mmdoptions.py
Labels: enhancement

#166 Bring Blender 4.3 Dev Uo to Date
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  ui/mmdoptions.py
Labels: enhancement

#167 Added end of life warning
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  ui/quickaccess.py
Labels: enhancement

#168 Bring Stable Up to Date
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  ui/quickaccess.py
Labels: Release Candidate

#169 Bring Stable Up To date 4.2
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  ui/mmdoptions.py
Labels: enhancement
