Repository teamneoneko/Cats-Blender-Plugin-Unofficial-, pull requests merged in 2025-01, with the labels that each got.

#264 Blender 42 dev
  __init__.py
  extentions.py
  resources/translations.csv
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/common.py
  tools/importer.py
  tools/material.py
  tools/translate.py
  ui/eye_tracking.py
  ui/mmdoptions.py
  ui/otheroptions.py
Labels: Release Candidate

#266 Blender 43 dev
  extentions.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/common.py
  tools/importer.py
  tools/material.py
  tools/translate.py
  ui/eye_tracking.py
  ui/mmdoptions.py
  ui/otheroptions.py
Labels: Release Candidate

#267 Added options to 'keep empty parent bones' and 'skip hidden bones' to delete zero weight bones
  extentions.py
  resources/translations.csv
  resources/translations/en_US.json
  tools/common.py
  ui/optimization.py
Labels: Release Candidate, Added

#271 Fixes and Additions
  extentions.py
  resources/translations/en_US.json
  tools/common.py
  ui/optimization.py
  updater.py
Labels: Added

#272 Fix updater not getting user preferences
  updater.py
Labels: Fixed

#283 Improvements and Cleanup
  tools/armature_manual.py
  tools/bonemerge.py
  ui/otheroptions.py
Labels: Release Candidate

#284 Improvements and Cleanup
  tools/armature_manual.py
  tools/bonemerge.py
  ui/otheroptions.py
Labels: Release Candidate

#285 Blender 42 dev
  __init__.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/armature_manual.py
  tools/bonemerge.py
  tools/common.py
  tools/importer.py
  ui/otheroptions.py
Labels: Release Candidate

#287 Blender 43 dev
  __init__.py
  resources/translations/en_US.json
  resources/translations/ja_JP.json
  resources/translations/ko_KR.json
  tools/armature_manual.py
  tools/bonemerge.py
  tools/common.py
  tools/importer.py
  ui/otheroptions.py
Labels: Release Candidate
